image: eclipse-temurin:21-jdk

stages:
  - build

variables:
  M2_HOME: ".m2/maven"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"

build:
  stage: build
  cache:
    paths:
      - .m2/
  script:
    - ./mvnw clean verify
